/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package other;

import com.sun.org.apache.xml.internal.dtm.DTM;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;

/**
 *
 * @author Ronila
 */
public class MyNewCustForm extends javax.swing.JFrame {

    /**
     * Creates new form MyNewCustForm
     */
    DefaultTableModel dtm1;
    DefaultTableModel dtm2;

    public MyNewCustForm() {
        initComponents();
        dtm1 = (DefaultTableModel) tblCustomer.getModel();
        dtm2 = (DefaultTableModel) tblCustomerReg.getModel();
        loadAllCustomers();
        txtcustID.requestFocus();
        setSize(1007, 475);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcustID = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtCustName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCustAddress = new javax.swing.JTextField();
        txtCustNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCustRegID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCustRegDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCustMail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnCustReg = new javax.swing.JButton();
        btnUpdateCust = new javax.swing.JButton();
        btnRemoveCust = new javax.swing.JButton();
        btnCustRefresh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomerReg = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ronila\\Downloads\\User Male_50px.png")); // NOI18N
        jLabel8.setText("Customer Manager Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        jLabel1.setText("Customer ID");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        jLabel2.setText("Customer Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, -1));

        txtcustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtcustID, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 493, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 129, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 36, -1, 138));

        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });
        jPanel3.add(txtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 94, 493, -1));

        jLabel3.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        jLabel3.setText("Customer Address");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 129, -1, -1));

        txtCustAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustAddressActionPerformed(evt);
            }
        });
        jPanel3.add(txtCustAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 152, 493, -1));

        txtCustNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNumActionPerformed(evt);
            }
        });
        jPanel3.add(txtCustNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 210, 493, -1));

        jLabel4.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        jLabel4.setText("Mobile Number");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 187, -1, -1));

        jLabel5.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        jLabel5.setText("Registration ID");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 187, -1, -1));

        txtCustRegID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustRegIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtCustRegID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 194, -1));

        jLabel6.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        jLabel6.setText("Registration Date");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 245, -1, -1));

        txtCustRegDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustRegDateActionPerformed(evt);
            }
        });
        jPanel3.add(txtCustRegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 268, 194, -1));

        jLabel7.setFont(new java.awt.Font("Felix Titling", 0, 13)); // NOI18N
        jLabel7.setText("E-Mail Address");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 245, -1, -1));

        txtCustMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustMailActionPerformed(evt);
            }
        });
        jPanel3.add(txtCustMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 268, 493, -1));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));

        btnCustReg.setText("Registor Customer");
        btnCustReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustRegActionPerformed(evt);
            }
        });

        btnUpdateCust.setText("Update Customer");
        btnUpdateCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustActionPerformed(evt);
            }
        });

        btnRemoveCust.setText("Remove Customer");
        btnRemoveCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCustActionPerformed(evt);
            }
        });

        btnCustRefresh.setText("Refresh");
        btnCustRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCustReg)
                            .addComponent(btnUpdateCust, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveCust, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnCustRefresh)))
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnCustReg)
                .addGap(45, 45, 45)
                .addComponent(btnUpdateCust)
                .addGap(45, 45, 45)
                .addComponent(btnRemoveCust)
                .addGap(36, 36, 36)
                .addComponent(btnCustRefresh)
                .addContainerGap())
        );

        tblCustomerReg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration ID", "Registration Date"
            }
        ));
        tblCustomerReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerRegMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCustomerReg);

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Registration ID", "Customer Name", "Customer Address", "Mobile Number ", "E-Mail Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCustomer);
        if (tblCustomer.getColumnModel().getColumnCount() > 0) {
            tblCustomer.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustIDActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myCustForm","root","cmjd49");
            String custID = txtcustID.getText();
            removeAllText();
            txtcustID.setText(custID);
            txtCustName.requestFocus();
            
            String sql = "Select custID,custName,custAddress,custNum,custMail from customer where custID=?";
            PreparedStatement pstm = connection.prepareStatement(sql);
            pstm.setObject(1, txtcustID.getText());
            ResultSet rst = pstm.executeQuery();
            while(rst.next()){
            txtcustID.setText(rst.getString(1));
            txtCustName.setText(rst.getString(2));
            txtCustAddress.setText(rst.getString(3));
            txtCustNum.setText(rst.getString(4));
            txtCustMail.setText(rst.getString(5));

            }
            
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyNewCustForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MyNewCustForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_txtcustIDActionPerformed

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
        txtCustAddress.requestFocus();
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void txtCustAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustAddressActionPerformed
        // TODO add your handling code here:
        txtCustNum.requestFocus();
    }//GEN-LAST:event_txtCustAddressActionPerformed

    private void txtCustNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNumActionPerformed
        // TODO add your handling code here:
        txtCustMail.requestFocus();
    }//GEN-LAST:event_txtCustNumActionPerformed

    private void txtCustMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustMailActionPerformed
        // TODO add your handling code here:
        txtCustRegID.requestFocus();
    }//GEN-LAST:event_txtCustMailActionPerformed

    private void txtCustRegIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustRegIDActionPerformed
        // TODO add your handling code here:
        txtCustRegDate.requestFocus();
    }//GEN-LAST:event_txtCustRegIDActionPerformed

    private void txtCustRegDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustRegDateActionPerformed
        // TODO add your handling code here:
        btnCustReg.requestFocus();
    }//GEN-LAST:event_txtCustRegDateActionPerformed

    private void btnCustRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustRegActionPerformed

        // TODO add your handling code here:
        
        try {

            String custID = txtcustID.getText();
            String custName = txtCustName.getText();
            String custAddress = txtCustAddress.getText();
            int custNum = Integer.parseInt(txtCustNum.getText());
            String custMail = txtCustMail.getText();
            String regID = txtCustRegID.getText();
            String regDate = txtCustRegDate.getText();

            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mycustform", "root", "cmjd49");

            
            

            String sql="insert into registration values (?,?)";
            PreparedStatement pstm1 = connection.prepareStatement(sql);
            
            
            pstm1.setObject(1, regID);
            pstm1.setObject(2, regDate);

            int i = pstm1.executeUpdate();
            
            sql = "insert into customer values(?,?,?,?,?,?)";
            PreparedStatement pstm2 = connection.prepareStatement(sql);
            
            pstm2.setObject(1,custID);
            pstm2.setObject(2, regID);
            pstm2.setObject(3,custName);
            pstm2.setObject(4,custAddress);
            pstm2.setObject(5,custNum);
            pstm2.setObject(6,custMail);
            
            i = pstm2.executeUpdate();
            
            
            if (i>0) {
                loadAllCustomers();
                JOptionPane.showMessageDialog(this, "Customer is registered", "Done", JOptionPane.INFORMATION_MESSAGE);
                removeAllText();
                txtcustID.requestFocus();
            } else{
                JOptionPane.showMessageDialog(this, "Customer is not registered", "Not Done", JOptionPane.ERROR_MESSAGE);
            }


            

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyNewCustForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCustRegActionPerformed

    private void btnRemoveCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCustActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myCustForm","root","cmjd49");
            String sql="Delete from registration where regID=?";
            
            PreparedStatement pstm = connection.prepareStatement(sql);
            pstm.setObject(1, txtCustRegID.getText());
            
            int i = pstm.executeUpdate();
            if(i>0){
            loadAllCustomers();
            JOptionPane.showMessageDialog(this, "Customer is Deleted", "Done", JOptionPane.INFORMATION_MESSAGE);
            removeAllText();;
            }else{
            JOptionPane.showMessageDialog(this, "Customer is not Deleted", "Warning", JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyNewCustForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnRemoveCustActionPerformed
            
    private void btnUpdateCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustActionPerformed
        try {
            // TODO add your handling code here:
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myCustForm","root","cmjd49");
            
            String sql = "update customer set custID=?,custName=?,custAddress=?,custNum=?,custMail=? where custID=?";
            PreparedStatement pstm1 = connection.prepareStatement(sql);
            pstm1.setObject(1, txtcustID.getText());
            pstm1.setObject(2, txtCustName.getText());
            pstm1.setObject(3, txtCustAddress.getText());
            pstm1.setObject(4, txtCustNum.getText());
            pstm1.setObject(5, txtCustMail.getText());
            pstm1.setObject(6, txtcustID.getText());
            
            int i = pstm1.executeUpdate();
            
            sql="update registration set regID=?,regDate=? where regID=?";
            pstm1 = connection.prepareStatement(sql);
            pstm1.setObject(1, txtCustRegID.getText());
            pstm1.setObject(2, txtCustRegDate.getText());
            pstm1.setObject(3, txtCustRegID.getText());
            
            pstm1.executeUpdate();

            if (i>0) {
                loadAllCustomers();
                JOptionPane.showMessageDialog(this, "Customer is updated", "Done", JOptionPane.INFORMATION_MESSAGE);
                
                removeAllText();
            }else{
            JOptionPane.showMessageDialog(this, "Customer is not updated", "Warning", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyNewCustForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Warning", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnUpdateCustActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblCustomer.getSelectedRow();

        txtcustID.setText(dtm1.getValueAt(selectedRow, 0).toString());
       
        txtCustName.setText(dtm1.getValueAt(selectedRow, 2).toString());
        txtCustAddress.setText(dtm1.getValueAt(selectedRow, 3).toString());
        txtCustNum.setText(dtm1.getValueAt(selectedRow, 4).toString());
        txtCustMail.setText(dtm1.getValueAt(selectedRow, 5).toString());

        txtCustRegID.setText(dtm2.getValueAt(selectedRow, 0).toString());
        txtCustRegDate.setText(dtm2.getValueAt(selectedRow, 1).toString());
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void btnCustRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustRefreshActionPerformed
        loadAllCustomers();
        removeAllText();
    }//GEN-LAST:event_btnCustRefreshActionPerformed

    private void tblCustomerRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerRegMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCustomerRegMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyNewCustForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyNewCustForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyNewCustForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyNewCustForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyNewCustForm().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustRefresh;
    private javax.swing.JButton btnCustReg;
    private javax.swing.JButton btnRemoveCust;
    private javax.swing.JButton btnUpdateCust;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblCustomerReg;
    private javax.swing.JTextField txtCustAddress;
    private javax.swing.JTextField txtCustMail;
    private javax.swing.JTextField txtCustName;
    private javax.swing.JTextField txtCustNum;
    private javax.swing.JTextField txtCustRegDate;
    private javax.swing.JTextField txtCustRegID;
    private javax.swing.JTextField txtcustID;
    // End of variables declaration//GEN-END:variables

    private void loadAllCustomers() {
        
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/myCustForm","root","cmjd49");
            
            String sql = "select * from customer";
            PreparedStatement pstm1 = connection.prepareStatement(sql);
            ResultSet rst = pstm1.executeQuery();
            dtm1.setRowCount(0);
            while(rst.next()){
            Object [] addRow={rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6)};
            dtm1.addRow(addRow);
            }
            PreparedStatement pstm2 = connection.prepareStatement(sql);
            sql="select * from registration";
            pstm2 = connection.prepareStatement(sql);
            rst = pstm2.executeQuery();
            
            dtm2.setRowCount(0);
            while(rst.next()){
            Object [] addRow={rst.getString(1),rst.getString(2)};
            dtm2.addRow(addRow);
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MyNewCustForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MyNewCustForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void removeAllText() {
        txtCustAddress.setText("");
        txtCustMail.setText("");
        txtCustName.setText("");
        txtCustNum.setText("");
        txtCustRegDate.setText("");
        txtCustRegID.setText("");
        txtcustID.setText("");
       

    }
}
